apiVersion: v1
kind: Namespace
metadata:
  name: hsblhsn
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: experiments.hsblhsn.me
  namespace: hsblhsn
spec:
  group: hsblhsn.me
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resume:
                  type: object
                  properties:
                    profile:
                      type: object
                      properties:
                        full_name:
                          type: string
                        introductory:
                          type: string
                    contact:
                      type: object
                      properties:
                        email:
                          type: string
                        phone:
                          type: string
                        address:
                          type: string
                        website:
                          type: string
                    work_experience:
                      type: array
                      items:
                        type: object
                        properties:
                          company:
                            type: string
                          position:
                            type: string
                          start_date:
                            type: string
                          end_date:
                            type: string
                          description:
                            type: string
                          highlights:
                            type: array
                            items:
                              type: string
                    education:
                      type: array
                      items:
                        type: object
                        properties:
                          institution:
                            type: string
                          degree:
                            type: string
                          description:
                            type: string
                          gpa:
                            type: string
                          start_date:
                            type: string
                          end_date:
                            type: string
                    skills:
                      type: array
                      items:
                        type: object
                        properties:
                          kind:
                            type: string
                          items:
                            type: array
                            items:
                              type: string
                    achievements:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          date:
                            type: string
                          awarder:
                            type: string
                          summary:
                            type: string
                    links:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          url:
                            type: string
  scope: Namespaced
  names:
    kind: Experiment
    plural: experiments
    singular: experiment
    categories:
      - hsblhsn
      - resume
      - ksume
    shortNames:
      - exp
      - exps
